# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cade16405e8ff8618cb946ad859ca4e30d3c3713ed4f80164b38986c2fdd38d795ba5f5c491e20806a207d3fcee720928d48b08eaba9e36e8e0f656dc2c73053

test:
  secret_key_base: bad374e44e2f1540c5061b9195b03fd8498dcbf4d2a72774c8ef531e80bb697504bbfea0a9fd20c45010b950a3bbe3e8fe41635db9f1bc73c92c0e12066d9ca7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
